## Color chart Excel파일로 만들기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image

In [4]:
img = Image.open('solar.png')
img.show()



x = np.array(img)
print(x)
print(x.shape)


[[[246 246 246 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [248 255 253 255]
  [252 254 253 255]
  [254 254 254 255]]

 [[201 201 201 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [230 254 251 255]
  [235 254 253 255]
  [239 254 254 255]]

 [[179 179 179 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [217 254 252 255]
  [221 254 254 255]
  [225 254 254 255]]

 ...

 [[ 65  64  70 255]
  [ 50  48  54 255]
  [ 52  51  55 255]
  ...
  [ 35  43  46 255]
  [ 36  44  46 255]
  [ 37  43  45 255]]

 [[ 65  64  70 255]
  [ 49  49  53 255]
  [ 51  50  54 255]
  ...
  [ 35  43  46 255]
  [ 35  43  45 255]
  [ 36  43  45 255]]

 [[ 65  64  70 255]
  [ 49  48  52 255]
  [ 50  50  52 255]
  ...
  [ 34  42  45 255]
  [ 34  42  44 255]
  [ 35  42  44 255]]]
(265, 334, 4)


In [46]:
#png 파일은 알파채널(투명도)을 따로 저장

rgb = x[:,:,:3]

In [54]:
rgb = np.array(img.convert("RGB"))

In [56]:
rgb.shape

(265, 334, 3)